name: vae_simple-dev
channels:
  - conda-forge
  - default
  - pytorch

dependencies:
  - python==3.9
  # environment management
  - pip

  # core dependencies
  - importlib-metadata>=1.5.0 # required if python < 3.8
  - pytorch>=1.9
  - pytorch-lightning>=1.5.10
  - torchvision>=0.11
  # TODO: add your dependencies here

  # demo package requirements
  - typing-extensions>=3.7.4.3 # required if python < 3.8
  - numpy>=1.19.1
  - pandas>=1.0.4
  - click>=7.1

  # testing and CI tools
  - nox>=2019.8.20
  - packaging>=20.0
  - dunamai>=1.0.0
  - mypy
  - black~=22.0
  - isort>=5.7.0
  - pytest>=5.3.5
  - pytest-cov>=2.8.1
  - pylint>=2.4.4
  - hypothesis[numpy]>=5.6.0

  # mypy types

  # packaging
  - twine
  - build

  - pip:
    - pylint-junit>=0.2.0
    # private sources below
    #- dummy-package (if installing from pypi)
    #- package @ git+ssh://git@github.com/blah/private-package.git@hash (if installing using ssh)
